[package]
name = "legado_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
dotenv = "0.15.0"
mongodb = "2.8.0"
serde = { version = "*", features = ["derive"] }
uuid = "1.6.1"
async-stripe = {version = "*" ,features = ["runtime-tokio-hyper"]}